#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phonebook
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PHONEBOOK")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Phonebook.Properties.Settings.Default.PHONEBOOKConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblPhoneBook> tblPhoneBooks
		{
			get
			{
				return this.GetTable<tblPhoneBook>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Delete")]
		public int sp_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), phID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_view")]
		public ISingleResult<sp_viewResult> sp_view()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_viewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Insert")]
		public void sp_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string phStudID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string phUsername, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string phPassword, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string phLast_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string phFirst_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string phMiddle_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string phAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phAge, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string phGender, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string phContactNum, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> phBirthDate)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), phStudID, phUsername, phPassword, phLast_Name, phFirst_Name, phMiddle_Name, phAddress, phAge, phGender, phContactNum, phBirthDate);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_mview")]
		public ISingleResult<sp_mviewResult> sp_mview()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_mviewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Search")]
		public ISingleResult<sp_SearchResult> sp_Search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string phLast_Name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), phLast_Name);
			return ((ISingleResult<sp_SearchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_StudentID")]
		public int sp_StudentID()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Update")]
		public void sp_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string phStudID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string phUsername, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string phPassword, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string phLast_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string phFirst_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string phMiddle_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string phAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> phAge, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string phGender, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string phContactNum, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> phBirthDate)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), phStudID, phUsername, phPassword, phLast_Name, phFirst_Name, phMiddle_Name, phAddress, phAge, phGender, phContactNum, phBirthDate);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPhoneBook")]
	public partial class tblPhoneBook
	{
		
		private int _phID;
		
		private string _phStudID;
		
		private string _phUsername;
		
		private string _phPassword;
		
		private string _phLast_Name;
		
		private string _phFirst_Name;
		
		private string _phMiddle_Name;
		
		private string _phAddress;
		
		private int _phAge;
		
		private string _phGender;
		
		private string _phContactNum;
		
		private System.Nullable<System.DateTime> _phBirthDate;
		
		public tblPhoneBook()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int phID
		{
			get
			{
				return this._phID;
			}
			set
			{
				if ((this._phID != value))
				{
					this._phID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phStudID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string phStudID
		{
			get
			{
				return this._phStudID;
			}
			set
			{
				if ((this._phStudID != value))
				{
					this._phStudID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phUsername", DbType="VarChar(30)")]
		public string phUsername
		{
			get
			{
				return this._phUsername;
			}
			set
			{
				if ((this._phUsername != value))
				{
					this._phUsername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phPassword", DbType="VarChar(30)")]
		public string phPassword
		{
			get
			{
				return this._phPassword;
			}
			set
			{
				if ((this._phPassword != value))
				{
					this._phPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phLast_Name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string phLast_Name
		{
			get
			{
				return this._phLast_Name;
			}
			set
			{
				if ((this._phLast_Name != value))
				{
					this._phLast_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phFirst_Name", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string phFirst_Name
		{
			get
			{
				return this._phFirst_Name;
			}
			set
			{
				if ((this._phFirst_Name != value))
				{
					this._phFirst_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phMiddle_Name", DbType="VarChar(20)")]
		public string phMiddle_Name
		{
			get
			{
				return this._phMiddle_Name;
			}
			set
			{
				if ((this._phMiddle_Name != value))
				{
					this._phMiddle_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phAddress", DbType="VarChar(100)")]
		public string phAddress
		{
			get
			{
				return this._phAddress;
			}
			set
			{
				if ((this._phAddress != value))
				{
					this._phAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phAge", DbType="Int NOT NULL")]
		public int phAge
		{
			get
			{
				return this._phAge;
			}
			set
			{
				if ((this._phAge != value))
				{
					this._phAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phGender", DbType="VarChar(10)")]
		public string phGender
		{
			get
			{
				return this._phGender;
			}
			set
			{
				if ((this._phGender != value))
				{
					this._phGender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phContactNum", DbType="VarChar(15)")]
		public string phContactNum
		{
			get
			{
				return this._phContactNum;
			}
			set
			{
				if ((this._phContactNum != value))
				{
					this._phContactNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phBirthDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> phBirthDate
		{
			get
			{
				return this._phBirthDate;
			}
			set
			{
				if ((this._phBirthDate != value))
				{
					this._phBirthDate = value;
				}
			}
		}
	}
	
	public partial class sp_viewResult
	{
		
		private int _phID;
		
		private string _phStudID;
		
		private string _phUsername;
		
		private string _phPassword;
		
		private string _phLast_Name;
		
		private string _phFirst_Name;
		
		private string _phMiddle_Name;
		
		private string _phAddress;
		
		private int _phAge;
		
		private string _phGender;
		
		private string _phContactNum;
		
		private System.Nullable<System.DateTime> _phBirthDate;
		
		public sp_viewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phID", DbType="Int NOT NULL")]
		public int phID
		{
			get
			{
				return this._phID;
			}
			set
			{
				if ((this._phID != value))
				{
					this._phID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phStudID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string phStudID
		{
			get
			{
				return this._phStudID;
			}
			set
			{
				if ((this._phStudID != value))
				{
					this._phStudID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phUsername", DbType="VarChar(30)")]
		public string phUsername
		{
			get
			{
				return this._phUsername;
			}
			set
			{
				if ((this._phUsername != value))
				{
					this._phUsername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phPassword", DbType="VarChar(30)")]
		public string phPassword
		{
			get
			{
				return this._phPassword;
			}
			set
			{
				if ((this._phPassword != value))
				{
					this._phPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phLast_Name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string phLast_Name
		{
			get
			{
				return this._phLast_Name;
			}
			set
			{
				if ((this._phLast_Name != value))
				{
					this._phLast_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phFirst_Name", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string phFirst_Name
		{
			get
			{
				return this._phFirst_Name;
			}
			set
			{
				if ((this._phFirst_Name != value))
				{
					this._phFirst_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phMiddle_Name", DbType="VarChar(20)")]
		public string phMiddle_Name
		{
			get
			{
				return this._phMiddle_Name;
			}
			set
			{
				if ((this._phMiddle_Name != value))
				{
					this._phMiddle_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phAddress", DbType="VarChar(100)")]
		public string phAddress
		{
			get
			{
				return this._phAddress;
			}
			set
			{
				if ((this._phAddress != value))
				{
					this._phAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phAge", DbType="Int NOT NULL")]
		public int phAge
		{
			get
			{
				return this._phAge;
			}
			set
			{
				if ((this._phAge != value))
				{
					this._phAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phGender", DbType="VarChar(10)")]
		public string phGender
		{
			get
			{
				return this._phGender;
			}
			set
			{
				if ((this._phGender != value))
				{
					this._phGender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phContactNum", DbType="VarChar(15)")]
		public string phContactNum
		{
			get
			{
				return this._phContactNum;
			}
			set
			{
				if ((this._phContactNum != value))
				{
					this._phContactNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phBirthDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> phBirthDate
		{
			get
			{
				return this._phBirthDate;
			}
			set
			{
				if ((this._phBirthDate != value))
				{
					this._phBirthDate = value;
				}
			}
		}
	}
	
	public partial class sp_mviewResult
	{
		
		private string _phstudid;
		
		private string _phusername;
		
		private string _phlast_name;
		
		private string _phfirst_name;
		
		private string _phmiddle_name;
		
		private string _phaddress;
		
		private int _phage;
		
		private string _phgender;
		
		private string _phcontactnum;
		
		private System.Nullable<System.DateTime> _phbirthdate;
		
		public sp_mviewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phstudid", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string phstudid
		{
			get
			{
				return this._phstudid;
			}
			set
			{
				if ((this._phstudid != value))
				{
					this._phstudid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phusername", DbType="VarChar(30)")]
		public string phusername
		{
			get
			{
				return this._phusername;
			}
			set
			{
				if ((this._phusername != value))
				{
					this._phusername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phlast_name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string phlast_name
		{
			get
			{
				return this._phlast_name;
			}
			set
			{
				if ((this._phlast_name != value))
				{
					this._phlast_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phfirst_name", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string phfirst_name
		{
			get
			{
				return this._phfirst_name;
			}
			set
			{
				if ((this._phfirst_name != value))
				{
					this._phfirst_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phmiddle_name", DbType="VarChar(20)")]
		public string phmiddle_name
		{
			get
			{
				return this._phmiddle_name;
			}
			set
			{
				if ((this._phmiddle_name != value))
				{
					this._phmiddle_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phaddress", DbType="VarChar(100)")]
		public string phaddress
		{
			get
			{
				return this._phaddress;
			}
			set
			{
				if ((this._phaddress != value))
				{
					this._phaddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phage", DbType="Int NOT NULL")]
		public int phage
		{
			get
			{
				return this._phage;
			}
			set
			{
				if ((this._phage != value))
				{
					this._phage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phgender", DbType="VarChar(10)")]
		public string phgender
		{
			get
			{
				return this._phgender;
			}
			set
			{
				if ((this._phgender != value))
				{
					this._phgender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phcontactnum", DbType="VarChar(15)")]
		public string phcontactnum
		{
			get
			{
				return this._phcontactnum;
			}
			set
			{
				if ((this._phcontactnum != value))
				{
					this._phcontactnum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phbirthdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> phbirthdate
		{
			get
			{
				return this._phbirthdate;
			}
			set
			{
				if ((this._phbirthdate != value))
				{
					this._phbirthdate = value;
				}
			}
		}
	}
	
	public partial class sp_SearchResult
	{
		
		private int _phID;
		
		private string _phStudID;
		
		private string _phUsername;
		
		private string _phPassword;
		
		private string _phLast_Name;
		
		private string _phFirst_Name;
		
		private string _phMiddle_Name;
		
		private string _phAddress;
		
		private int _phAge;
		
		private string _phGender;
		
		private string _phContactNum;
		
		private System.Nullable<System.DateTime> _phBirthDate;
		
		public sp_SearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phID", DbType="Int NOT NULL")]
		public int phID
		{
			get
			{
				return this._phID;
			}
			set
			{
				if ((this._phID != value))
				{
					this._phID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phStudID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string phStudID
		{
			get
			{
				return this._phStudID;
			}
			set
			{
				if ((this._phStudID != value))
				{
					this._phStudID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phUsername", DbType="VarChar(30)")]
		public string phUsername
		{
			get
			{
				return this._phUsername;
			}
			set
			{
				if ((this._phUsername != value))
				{
					this._phUsername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phPassword", DbType="VarChar(30)")]
		public string phPassword
		{
			get
			{
				return this._phPassword;
			}
			set
			{
				if ((this._phPassword != value))
				{
					this._phPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phLast_Name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string phLast_Name
		{
			get
			{
				return this._phLast_Name;
			}
			set
			{
				if ((this._phLast_Name != value))
				{
					this._phLast_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phFirst_Name", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string phFirst_Name
		{
			get
			{
				return this._phFirst_Name;
			}
			set
			{
				if ((this._phFirst_Name != value))
				{
					this._phFirst_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phMiddle_Name", DbType="VarChar(20)")]
		public string phMiddle_Name
		{
			get
			{
				return this._phMiddle_Name;
			}
			set
			{
				if ((this._phMiddle_Name != value))
				{
					this._phMiddle_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phAddress", DbType="VarChar(100)")]
		public string phAddress
		{
			get
			{
				return this._phAddress;
			}
			set
			{
				if ((this._phAddress != value))
				{
					this._phAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phAge", DbType="Int NOT NULL")]
		public int phAge
		{
			get
			{
				return this._phAge;
			}
			set
			{
				if ((this._phAge != value))
				{
					this._phAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phGender", DbType="VarChar(10)")]
		public string phGender
		{
			get
			{
				return this._phGender;
			}
			set
			{
				if ((this._phGender != value))
				{
					this._phGender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phContactNum", DbType="VarChar(15)")]
		public string phContactNum
		{
			get
			{
				return this._phContactNum;
			}
			set
			{
				if ((this._phContactNum != value))
				{
					this._phContactNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phBirthDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> phBirthDate
		{
			get
			{
				return this._phBirthDate;
			}
			set
			{
				if ((this._phBirthDate != value))
				{
					this._phBirthDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
