<?xml version="1.0" encoding="utf-8"?><Database Name="PHONEBOOK" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NATHANIEL;Initial Catalog=PHONEBOOK;Integrated Security=True" SettingsObjectName="Phonebook.Properties.Settings" SettingsPropertyName="PHONEBOOKConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblPhoneBook" Member="tblPhoneBooks">
    <Type Name="tblPhoneBook">
      <Column Name="phID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="phStudID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="phUsername" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="phPassword" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="phLast_Name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="phFirst_Name" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="phMiddle_Name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="phAddress" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="phAge" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="phGender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="phContactNum" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="phBirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_Delete" Method="sp_Delete">
    <Parameter Name="phID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_view" Method="sp_view">
    <ElementType Name="sp_viewResult">
      <Column Name="phID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="phStudID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="phUsername" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="phPassword" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="phLast_Name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="phFirst_Name" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="phMiddle_Name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="phAddress" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="phAge" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="phGender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="phContactNum" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="phBirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Insert" Method="sp_Insert">
    <Parameter Name="phStudID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="phUsername" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="phPassword" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="phLast_Name" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="phFirst_Name" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="phMiddle_Name" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="phAddress" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="phAge" Type="System.Int32" DbType="Int" />
    <Parameter Name="phGender" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="phContactNum" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="phBirthDate" Type="System.DateTime" DbType="DateTime" />
  </Function>
  <Function Name="dbo.sp_mview" Method="sp_mview">
    <ElementType Name="sp_mviewResult">
      <Column Name="phstudid" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="phusername" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="phlast_name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="phfirst_name" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="phmiddle_name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="phaddress" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="phage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="phgender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="phcontactnum" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="phbirthdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Search" Method="sp_Search">
    <Parameter Name="phLast_Name" Type="System.String" DbType="VarChar(30)" />
    <ElementType Name="sp_SearchResult">
      <Column Name="phID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="phStudID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="phUsername" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="phPassword" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="phLast_Name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="phFirst_Name" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="phMiddle_Name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="phAddress" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="phAge" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="phGender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="phContactNum" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="phBirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_StudentID" Method="sp_StudentID">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Update" Method="sp_Update">
    <Parameter Name="phStudID" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="phUsername" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="phPassword" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="phLast_Name" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="phFirst_Name" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="phMiddle_Name" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="phAddress" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="phAge" Type="System.Int32" DbType="Int" />
    <Parameter Name="phGender" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="phContactNum" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="phBirthDate" Type="System.DateTime" DbType="DateTime" />
  </Function>
</Database>